package com.solodream.spring.vertx.jpa.domain;

import com.solodream.spring.vertx.jpa.model.base.BaseBean;

import java.util.Date;

/**
 * PoiInfo
 * 
 * @author Auto generated by solodream.com
 * @since 2015-09-24 00:18:16
 * @version 1.0
 */
public class PoiInfoDto extends BaseBean {

	private static final long serialVersionUID = -1L;

	/**
	 * 客户公司ID
	 */
	private String orgId;

	/**
	 * 名字
	 */
	private String name;

	/**
	 * 详细地址
	 */
	private String address;

	/**
	 * 邮编
	 */
	private String postcode;

	/**
	 * 描述（如某酒店门口）
	 */
	private String description;

	/**
	 * 经度
	 */
	private String lng;

	/**
	 * 纬度
	 */
	private String lat;

	/**
	 * 半径（单位:米）
	 */
	private String radius;

	/**
	 * json
	 */
	private String intervalTime;

	private Date stationStartTime;

	private String customerId;

	private String customerName;


	private String customerPhone;

	private String updateBy;

	private String contractId;

	private String companyId;

	private String companyName;

	private String type;

	public String getContractId() {
		return contractId;
	}

	public void setContractId(String contractId) {
		this.contractId = contractId;
	}

	public String getCustomerId() {
		return customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public String getCustomerName() {
		return customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getUpdateBy() {
		return updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public Date getStationStartTime() {
		return stationStartTime;
	}

	public void setStationStartTime(Date stationStartTime) {
		this.stationStartTime = stationStartTime;
	}

	public String getIntervalTime() {
		return intervalTime;
	}

	public void setIntervalTime(String intervalTime) {
		this.intervalTime = intervalTime;
	}

	/**
	 * 客户公司ID
	 *
	 * @return
	 */
	public String getOrgId() {
		return this.orgId;
	}

	/**
	 * 客户公司ID
	 *
	 * @param orgId
	 */
	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	/**
	 * 名字
	 *
	 * @return
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * 名字
	 *
	 * @param name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * 详细地址
	 *
	 * @return
	 */
	public String getAddress() {
		return this.address;
	}

	/**
	 * 详细地址
	 *
	 * @param address
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * 邮编
	 *
	 * @return
	 */
	public String getPostcode() {
		return this.postcode;
	}

	/**
	 * 邮编
	 *
	 * @param postcode
	 */
	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	/**
	 * 经度
	 *
	 * @return
	 */
	public String getLng() {
		return this.lng;
	}

	/**
	 * 经度
	 *
	 * @param lng
	 */
	public void setLng(String lng) {
		this.lng = lng;
	}

	/**
	 * 纬度
	 *
	 * @return
	 */
	public String getLat() {
		return this.lat;
	}

	/**
	 * 纬度
	 *
	 * @param lat
	 */
	public void setLat(String lat) {
		this.lat = lat;
	}

	/**
	 * 半径（单位:米）
	 *
	 * @return
	 */
	public String getRadius() {
		return this.radius;
	}

	/**
	 * 半径（单位:米）
	 *
	 * @param radius
	 */
	public void setRadius(String radius) {
		this.radius = radius;
	}

	public String getCompanyId() {
		return companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getCustomerPhone() {
		return customerPhone;
	}

	public void setCustomerPhone(String customerPhone) {
		this.customerPhone = customerPhone;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
