package com.solodream.spring.vertx.mapper;

import com.solodream.spring.vertx.jpa.domain.PoiInfoDto;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * PoiInfoMapper
 *
 * @author Auto generated by solodream.com
 * @version 1.0
 * @since 2015-09-24 00:18:16
 */
public interface PoiInfoMapper {

    public int insert(PoiInfoDto dto);

    public void update(@Param("poiInfo") PoiInfoDto dto);

    public void delete(int id);

    public void deletes(List<Integer> id);

    public void deletePoiByCustomer(List<Integer> id);

    public PoiInfoDto get(int id);

    public List<PoiInfoDto> gets(List<Integer> id);

    public PoiInfoDto query(@Param("poiInfo") PoiInfoDto dto, @Param("keyword") String keyword);

    public List<PoiInfoDto> querys(@Param("poiInfo") PoiInfoDto dto, @Param("keyword") String keyword);

    public int count(@Param("poiInfo") PoiInfoDto dto, @Param("keyword") String keyword);

    public List<PoiInfoDto> list(@Param("poiInfo") PoiInfoDto dto, @Param("keyword") String keyword, @Param("offset") int offset, @Param("length") int length);

    public List<PoiInfoDto> listAll();

    // //
}