package com.solodream.spring.vertx.mapper;

import com.solodream.spring.vertx.jpa.domain.ClientAccountInfoDto;
import org.apache.ibatis.annotations.Param;

/**
 * UserMapper
 *
 * @author Auto generated by solodream.com
 * @version 1.0
 * @since 2015-10-09 23:18:59
 */
public interface UserMapper {

    public ClientAccountInfoDto get(int id);


    public ClientAccountInfoDto query(@Param("tbContractInfo") ClientAccountInfoDto dto);


    public int count(@Param("TbContractInfoIInfo") ClientAccountInfoDto dto, @Param("keyword") String keyword);

}